FORMAT: 1A
HOST: http://sweetoutdoors.me

# SWEetOutdoors

SWEetOudoors is a handy API to retrieve centralized data regarding outdoor parks along with campgrounds and events in those parks.

Find the website at: sweetoutdoors.me


# group Parks 

## All Parks [/parks]

### List Of All Parks [GET]

+ Response 200 (application/json)

        [
            {
                "id": "0",
                "name": "McKinney Falls State Park"
            },
            {
                "id": "1",
                "name": "Death Valley National Park"
            },
            {
                "id": "2",
                "name": "Big Bend National Park"
            }
        ]

## Specific Park [/parks/{park_id}]

+ Parameters
    + park_id (number) - id of the requested park in the form of an integer

### Specific Park [GET]

+ Response 201 (application/json)

        [
            {
                "idnum": "2",
                "name": "Big Bend National Park",
                "latitude": "29.1275",
                "longitude": "103.2425",
                "address": "PO Box 129 Big Bend National Park",
                "phone": "(432) 477-2251",
                "rating": "4.7",
                "website": "https://www.nps.gov/bibe/index.htm",
                "zipcode": "79834",
                "photo_url": "https://farm3.staticflickr.com/2814/11052915046_4be39145f4_b.jpg",
                "zipregion": "798",
                "state_id_fk": "0"
            }
        ]
        

# group States 

## All States [/states]

### List Of All States [GET]

+ Response 300 (application/json)

        [
            {
                "id": "0",
                "name": "Texas"
            },
            {
                "id": "1",
                "name": "California"
            },
            {
                "id": "2",
                "name": "Florida"
            }
        ]

## Specific State [/states/{state_id}]

+ Parameters
    + state_id (number) - id of the requested state in the form of an integer

### Specific State [GET]

+ Response 301 (application/json)

        [
            {
                "idnum": "0",
                "name": "Texas",
                "highestPoint": "1522341234",
                "population": "6212345",
                "description": "Texas is the second largest state in the United States by both area and population. Geographically located in the south central part of the country, Texas shares borders with the other US states of Louisiana to the east, Arkansas to the northeast, Oklahoma to the north, New Mexico to the west, and the Mexican states of Chihuahua, Coahuila, Nuevo León, and Tamaulipas to the southwest, while the Gulf of Mexico is to the southeast.",
                "totalArea": "123456"
            }
        ]
        

# group Events 

## All Events [/events]

### List Of All Events [GET]

+ Response 400 (application/json)

        [
            {
                "id": "0",
                "name": "Austin City Limits"
            },
            {
                "id": "1",
                "name": "Run For The Hungry"
            },
            {
                "id": "2",
                "name": "Yellowstone Anniversary"
            }
        ]

## Specific Event [/events/{event_id}]

+ Parameters
    + event_id (number) - id of the requested event in the form of an integer

### Specific Event [GET]

+ Response 401 (application/json)

        [
            {
                "idnum": "0",
                "name": "Austin City Limits",
                "latitude": "235.34",
                "longitude": "172.83",
                "topics": "Music",
                "start_date": "2016-11-28",
                "end_date": "2016-11-30",
                "pic_url": "http://cdn2.pitchfork.com/news/61374/caf49867.jpg",
                "org_name": "Austin Parks Foundation",
                "contact_phone_num": "(888) 512-7469",
                "city": "Austin",
                "zipcode": "78705",
                "zipregion": "787",
                "state_id_fk": "0"
            }
        ]
        

# group Campgrounds 

## All Campgrounds [/campground]

### List Of All Campgrounds [GET]

+ Response 500 (application/json)

        [
            {
                "id": "0",
                "name": "Yosemite Campground"
            },
            {
                "id": "1",
                "name": "Bear Creek"
            },
            {
                "id": "2",
                "name": "Everglades Campground"
            }
        ]

## Specific Campground [/campgrounds/{campground_id}]

+ Parameters
    + campground_id (number) - id of the requested campground in the form of an integer

### Specific Campground [GET]

+ Response 501 (application/json)

        [
            {
                "idnum": "0",
                "name": "Yosemite Campground",
                "description": "campground",
                "longitude": "68.12",
                "latitude": "123.643",
                "direction": "go right",
                "phone": "(209) 372-0200",
                "email": "email@gmail.com",
                "zipcode": "95389",
                "state_id_fk": "1"
            }
        ]